[fonts]
packages = [
  "source-code-pro",
  "font-awesome_5",
  "font-awesome_4",
  "noto-fonts-emoji",
  "nerd-fonts.symbols-only",

  # Fallback font! See https://shkspr.mobi/blog/2019/04/banish-the-%ef%bf%bd-with-unifont/
  "unifont",
  "unifont_upper",
]

[fonts.fontconfig.defaultFonts]
monospace = [ "Source Code Pro" ]
emoji = [ "Noto Color Emoji" ]
