environment.systemPackages = [
    # Dmenu-like launcher/menu
    "fuzzel",
    # Default terminal
    "alacritty",
    # X11 compatibility
    "xwayland-satellite",
    # Wallpaper daemon
    "swww",

    # Notification daemon
    # "mako",
    # Portals
    "xdg-desktop-portal-gtk", # implements most of the basic functionality, this is the "default fallback portal".
    "xdg-desktop-portal-gnome", # required for screencasting support.

    # Change display brightness, needs some additional rights
    "brightnessctl",
    # Allow clipboard management from the CLI
    "wl-clipboard",
]

[programs.niri]
enable = true

[programs.waybar]
enable = true

[services.displayManager]
enable = true
defaultSession = "none+niri"
